"""add_last_synced_at_to_accounts

Revision ID: 00943b009a77
Revises: complete_automation_rules_schema
Create Date: 2025-07-28 22:22:00.576780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00943b009a77'
down_revision: Union[str, Sequence[str], None] = 'complete_automation_rules_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('automation_rules_rule_id_key'), 'automation_rules', type_='unique')
    op.drop_index(op.f('ix_automation_rules_rule_id'), table_name='automation_rules')
    op.create_index(op.f('ix_automation_rules_rule_id'), 'automation_rules', ['rule_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_rule_id'), table_name='automation_rules')
    op.create_index(op.f('ix_automation_rules_rule_id'), 'automation_rules', ['rule_id'], unique=False)
    op.create_unique_constraint(op.f('automation_rules_rule_id_key'), 'automation_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('accounts', 'last_synced_at')
    # ### end Alembic commands ###
